### ISSUE TITLE
TypeError:'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by wyb081** [linan142857/BRCN#1]
![image](https://cloud.githubusercontent.com/assets/23629831/26233995/01fa4564-3c94-11e7-964a-55396be312fd.png)

你好，非常感谢你分享的代码，我在重复你的代码时总是会报错
lr_data = np.asarray(f.get('lr_data')[:], dtype=config.floatX).T
TypeError:'NoneType' object has no attribute '__getitem__'

请问这个错误应该怎么解决呢?

**Comment by yuanshuai220** [comment]
我也有这个问题
```

(theano) E:\BRCN-master\src>python brcn.py
... Loading data
Traceback (most recent call last):
  File "brcn.py", line 599, in <module>
    train_brnn(max_epochs=30)
  File "brcn.py", line 476, in train_brnn
    valid_set_x, valid_set_y = load_data(v)
  File "brcn.py", line 273, in load_data
    lr_data = np.asarray(f.get('lr_data')[:], dtype=config.floatX).T
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by linan142857** [comment]
Did you generate the train or test dataset(.mat)？
Make sure that you have run the yuv2png.m and process_data.m to create dataset file.

**Comment by linan142857** [comment]
@wyb081 @yuanshuai220 
Did you generate the train or test datasets？
./videos/*.7z are compressed videos. 
1. decompress above files.
2. convert the .yuv videos to images by  yuv2png.m.
3. run process_data.m and process_test_data.m to create train/test data files(.mat).

Make sure that you have completed those steps before training .
