### ISSUE TITLE
process_test_data.m Problem?

### ISSUE THREAD

**Issue by yaokx** [linan142857/BRCN#2]
你好，Matlab运行process_test_data.m的时候提示“Undefined function or variable 'modcrop'.”，缺少modcrop这个函数。

**Comment by linan142857** [comment]
@yaokx 不好意思，我已经添加上去了

**Comment by yaokx** [comment]
可以了，非常感谢。你好，可以加我qq吗，有问题请教你 292865798

**Comment by linan142857** [comment]
@yaokx 额，我基本不上qq的，你可以给我发邮件啊，这个 yulin.li@vipl.ict.ac.cn
