### ISSUE TITLE
brcn.py-run problem

### ISSUE THREAD

**Issue by yaokx** [linan142857/BRCN#3]
你好，运行brcn.py的时候报错，提示“AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'”

**Comment by linan142857** [comment]
@yaokx python3 和 2不一样，iteritems -> items

**Comment by yaokx** [comment]
运行brcn.py的时候报错，提示“OSError: Unable to create file (unable to open file: name = '../data/test/58_Dirty_Dancing_scale4_blur_2.mat', errno = 17, error message = 'File exists', flags = 15, o_flags = 502)”
