### ISSUE TITLE
How to test the model?

### ISSUE THREAD

**Issue by xhsoldier** [linan142857/BRCN#6]
Is there any test code that can run directly without training?

**Comment by linan142857** [comment]
@xhsoldier Sorry, the test code is involved in training stage for convenience.

**Comment by BSYMAHESH** [comment]
Hi, How can i test BRCN on my own data. Can you help me regarding this

**Comment by linan142857** [comment]
@BSYMAHESH @xhsoldier I add `test_brnn` in brcn.py

**Comment by BSYMAHESH** [comment]
Thanks for sharing test_brnn code. But got an error when i try to run test_brnn. can you help me how to resolve this.

Here is the errror i got..

% python brcn.py
... Loading data
model options {'padding': 6, 'rec_filter_size': [[64, 64, 1, 1], [32, 32, 1, 1]], 'filter_shape': [[64, 1, 9, 9], [32, 64, 1, 1], [1, 32, 5, 5]], 'model_path': '14_seq_41085_yuv_scala_4_frm10_blur_2.npy'}
... Building model
... Test data
 ...Test_PSNR:  OrderedDict()

**Comment by linan142857** [comment]
@BSYMAHESH sorry, i wrongly  write `test_set` as `test_psnr` in line 653.
